spring:
  datasource:
    url: jdbc:postgresql://localhost:8081/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
  messages:
    basename: validation
server:
  port: 8085