spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
  main:
    banner-mode: log
  datasource:
    url: jdbc:postgresql://localhost:8081/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: none
  messages:
    basename: validation
  security:
    user:
      name: username
      password: 12345678
logging:
  level:
    org.springframework.jdbc.core: TRACE
  file:
    name: person-service.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 5MB
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, loggers"
server:
  port: 8085